"use client";

import { useMemo, useState } from "react";
import { format } from "date-fns";
import { useAgent } from "./AgentProvider";
import type { AgentTaskStatus, Priority } from "@/lib/types";
import { generateId } from "@/lib/id";

const statusLabels: Record<AgentTaskStatus, string> = {
  pending: "Queued",
  "in-progress": "In motion",
  review: "Awaiting review",
  completed: "Completed"
};

const statusColors: Record<AgentTaskStatus, string> = {
  pending: "bg-slate-100 text-slate-600",
  "in-progress": "bg-brand-100 text-brand-700",
  review: "bg-amber-100 text-amber-700",
  completed: "bg-emerald-100 text-emerald-700"
};

export function TaskBoard() {
  const { tasks, addTask, updateTaskStatus, appendLog } = useAgent();
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [channel, setChannel] = useState("Omnichannel");
  const [priority, setPriority] = useState<Priority>("medium");

  const groupedTasks = useMemo(() => {
    return tasks.reduce<Record<AgentTaskStatus, typeof tasks>>(
      (acc, task) => {
        acc[task.status] = acc[task.status] || [];
        acc[task.status].push(task);
        return acc;
      },
      {
        pending: [],
        "in-progress": [],
        review: [],
        completed: []
      }
    );
  }, [tasks]);

  const handleSubmit = () => {
    if (!title.trim()) return;
    const now = new Date().toISOString();
    const newTask = {
      id: generateId("task"),
      title: title.trim(),
      status: "pending" as AgentTaskStatus,
      priority,
      channel,
      owner: "Aeon Agent",
      due: now,
      tags: ["autogenerated"],
      description: description.trim() || "Generated by agent command center"
    };
    addTask(newTask);
    appendLog({
      id: generateId("log"),
      actor: "Aeon Agent",
      icon: "🧠",
      status: "success",
      summary: `Task queued: ${newTask.title}`,
      timestamp: now
    });
    setTitle("");
    setDescription("");
  };

  return (
    <section className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-slate-900">Operational runway</h2>
          <p className="text-sm text-slate-500">
            The agent sequences product, merchandising, and loyalty tasks across channels.
          </p>
        </div>
        <div className="flex w-full flex-col gap-2 md:w-auto md:flex-row">
          <input
            className="w-full rounded-xl border border-slate-200 px-4 py-2 text-sm focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-100"
            placeholder="New directive e.g. 'Launch Meta catalog ads'"
            value={title}
            onChange={(event) => setTitle(event.target.value)}
          />
          <select
            className="rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-600 focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-100"
            value={priority}
            onChange={(event) => setPriority(event.target.value as Priority)}
          >
            <option value="low">Low priority</option>
            <option value="medium">Medium priority</option>
            <option value="high">High priority</option>
            <option value="urgent">Mission critical</option>
          </select>
          <button
            className="whitespace-nowrap rounded-xl bg-brand-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-brand-700"
            onClick={handleSubmit}
          >
            Autonomously assign
          </button>
        </div>
      </header>

      <div className="grid gap-4 md:grid-cols-4">
        {(Object.keys(groupedTasks) as AgentTaskStatus[]).map((status) => (
          <div key={status} className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-slate-700">{statusLabels[status]}</h3>
              <span className={`rounded-full px-2 py-0.5 text-xs ${statusColors[status]}`}>
                {groupedTasks[status].length}
              </span>
            </div>
            <div className="space-y-3">
              {groupedTasks[status].map((task) => (
                <div key={task.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="text-sm font-medium text-slate-900">{task.title}</p>
                      <p className="text-xs uppercase text-slate-400">Priority: {task.priority}</p>
                    </div>
                    <select
                      className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs text-slate-500"
                      value={task.status}
                      onChange={(event) => updateTaskStatus(task.id, event.target.value as AgentTaskStatus)}
                    >
                      <option value="pending">Queued</option>
                      <option value="in-progress">In motion</option>
                      <option value="review">Review</option>
                      <option value="completed">Completed</option>
                    </select>
                  </div>
                  <p className="mt-2 text-xs text-slate-500">{task.description}</p>
                  <div className="mt-3 flex items-center justify-between text-xs text-slate-500">
                    <span>{task.channel}</span>
                    <span>{format(new Date(task.due), "MMM d, HH:mm")}</span>
                  </div>
                </div>
              ))}
              {groupedTasks[status].length === 0 ? (
                <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-4 text-center text-xs text-slate-400">
                  Awaiting agent directives
                </div>
              ) : null}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
